version: "3.7"
services:
  ruby:
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
    container_name: "ruby"
    volumes:
      - .:/app
    networks:
      - app-network
  database:
    image: postgres:11.4
    environment:
      - PG_TRUST_LOCALNET=true
    networks:
      - app-network
  webserver:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: "webserver"
    volumes:
      - .:/app
    ports:
      - "3000:80"
    # depends_on:
    #   - ruby
    networks:
      - app-network
networks:
  app-network:
    name: app-network
    driver: bridge
